---

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  tags:
    - apt
    - update_cache

- name: Install uwsgi package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_uwsgi_package_dependencies
  when: uwsgi_package_dependencies is defined
  with_items: "{{ uwsgi_package_dependencies | defaul([]) }}"
  tags:
    - apt
    - dependencies
- debug: var=install_uwsgi_package_dependencies.stdout_lines

- name: Install uwsgi dependencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_uwsgi_dependencies
  when: uwsgi_dependencies is defined
  with_items: "{{ uwsgi_dependencies | defaul({}) }}"
  tags:
    - apt
    - dependencies
- debug: var=install_uwsgi_dependencies.stdout_lines
