---
- name: Create files
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: _uwsgi_create_files
  when: _uwsgi_create_files is defined
